### ISSUE TITLE
Update to latest version for python-ecmwf_grib

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/ecmwf_grib-feedstock#11]
@kmuehlbauer we need to update here first. Are you doing it or do you want me to do it?

**Comment by kmuehlbauer** [comment]
@ocefpaf I'm a bit short of time now, If you can do this, would be perfect. Do I need to change this PR?

**Comment by ocefpaf** [comment]
> @ocefpaf I'm a bit short of time now, If you can do this, would be perfect.

Sure.

> Do I need to change this PR? Nope.
