### ISSUE TITLE
FYI: CCSDS encoding patch

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/ecmwf_grib-feedstock#13]
Found this patch which corrects/adapts ccsds-encoding. This is just FYI, if some problems with this arise. This should be incorporated with the next gribapi-release.

https://gist.github.com/erget/9664a4307f1ed9092675faee47cbd6df

[Reference document at WMO](https://www.wmo.int/pages/prog/www/ISS/Meetings/IPET-DRMM_Geneva2016/Documents/IPET-DRMM-IV_Doc4-2-1-1_ccsdsValidationReport.docx)

**Comment by ocefpaf** [comment]
Thanks @kmuehlbauer! Is it worth adding that patch now or can we wait for the next release?

**Comment by kmuehlbauer** [comment]
I'd do this only if requested by users.

**Comment by ocefpaf** [comment]
Agreed. (Sadly (or luckily?) most users don't know about the `feedstock` model and were to report issues :wink: )

**Comment by kynan** [comment]
This is fixed in ecCodes 2.0.0.
