### ISSUE TITLE
Need rebuild

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/ecmwf_grib-feedstock#2]
Packages are currently linked to jpeg8; need to rebuild against jpeg9.

**Comment by ocefpaf** [comment]
I re-started the CIs and, even though I can see that jasper is picking the latest `jpeg`, the issue persisted. I need to take a closer look at this later, but I will be away from office for a while.

**Comment by dopplershift** [comment]
Right, the jasper packages are linked against jpeg9. However, I think the grib_api picked up jpeg8 (for some reason), so it's the grib_api libraries that need a rebuild to get jpeg9.

**Comment by ocefpaf** [comment]
I will trigger a re-build there as soon as I get back.

**Comment by dopplershift** [comment]
Solved. Thanks! 🎉

**Comment by pelson** [comment]
Again, wish we had https://github.com/conda/conda-build/pull/747
