### ISSUE TITLE
It seems that Windows is possible

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/ecmwf_grib-feedstock#5]
https://software.ecmwf.int/wiki/pages/viewpage.action?pageId=48109524

**Comment by pelson** [comment]
Yes, they have experimental support in one of the later versions of grib_api, and ecCodes also has Windows support (but ecCodes is beta).

**Comment by pelson** [comment]
Ping @0x1mason - I know you are in this space (thanks for the pointer at https://github.com/SciTools/conda-recipes-scitools/issues/150).

**Comment by 0x1mason** [comment]
Yes. I haven't worked with the latest version, but I have 1.14.5 building without issue for x86 and x64. I also added Win32 multithreading support via OMP (granted MT not really an issue with Python). You can  take a gander at https://github.com/0x1mason/GribApi.XP/tree/master/grib_api .

You can download the console apps via chocolately if you want to play with it. I haven't been using it, but I assume it works 😃

I be happy to help you work through any any issues you have integrating. I know Python and have done a little native code integration.

**Comment by ARF1** [comment]
What is the status on this? Is there anything blocking it? What would be necessary to make this work?

**Comment by ocefpaf** [comment]
@ARF1 see https://software.ecmwf.int/wiki/pages/viewpage.action?pageId=48109524

**Comment by ocefpaf** [comment]
Closing this so we can focus on eccodes instead. If anyone is interested in sending a PR I'll gladly review it.
